project:
  type: website
  output-dir: .

website:
  title: "Gary Chang"
  description: "Data/GIS Scientist, Researcher, Systems Engineer"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: certificates.qmd
        text: Certificates
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/gchang1020
        aria-label: GitHub

  page-footer:
    center: |
      © 2025 Gary Chang

format:
  html:
    theme:
      - cosmo
      - brand.scss
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
