---
title: "Certificates"
toc: false
---

## Awards
- **Fred Hill Endowed Scholarship**<br>
	*University of Texas at Dallas · 2025*

## Academic Certifications

- **Graduate Certificate Geospatial Information Sciences**<br>
	*University of Texas at Dallas · 2025*

- **Graduate Teaching Certificate**<br>
	*University of Texas at Dallas · 2024*

## ESRI / ArcGIS Training Certificates

- Deep Learning Using ArcGIS Pro
- Integrating R Scripts into ArcGIS Geoprocessing Tools
- Mapping Clusters: Hot Spot and Cluster and Outlier Analysis
- Mapping Clusters: Optimized Hot Spot and Optimized Outlier Analysis
- Mapping Clusters: Introduction to Statistical Cluster Analysis
- Regression Analysis: Building a Regression Model Using ArcGIS Pro
- Regression Analysis: Performing Random Forest Regression Using ArcGIS Pro
- Spatial Data Science: The New Frontier in Analytics
- Suitability Modeling: Creating a Weighted Suitability Model
- Suitability Modeling: Creating a Simple Suitability Model
- Using the R-ArcGIS Bridge
